# Generated by Django 5.1.7 on 2025-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
